# Generated by Django 3.1.6 on 2024-04-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('dono', models.CharField(default='', max_length=255)),
                ('raca_pet', models.CharField(default='', max_length=255)),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('fêmea', 'Fêmea')], default='', max_length=10)),
                ('categoria_pet', models.CharField(default='', max_length=255)),
                ('peso', models.CharField(default='', max_length=255)),
                ('altura', models.CharField(default='', max_length=255)),
                ('cor_pet', models.CharField(default='', max_length=255)),
                ('vacinas_pet', models.TextField(default='')),
                ('motivo_entrada_pet', models.CharField(default='', max_length=255)),
                ('tipo_entrega', models.CharField(choices=[('retirada', 'Retirada'), ('à domicilio', 'À domicilio'), ('não se aplica', 'Não se aplica')], default='', max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='animal_imagens/%Y/%m/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
            },
        ),
        migrations.CreateModel(
            name='Dono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dono', models.CharField(blank=True, max_length=50, null=True)),
                ('contato', models.CharField(blank=True, max_length=11, null=True)),
                ('CPF', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'verbose_name': 'Dono',
                'verbose_name_plural': 'Donos',
            },
        ),
    ]
